name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
      # Add this step to install a specific CMake version
    - name: Set up CMake
      uses: lukka/get-cmake@v3.29.0 # Use the latest version of get-cmake, or a specific CMake version
      with:
        cmakeVersion: "4.0.3" # Or "4.0.3"
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

